function [xStep,yStep,trueAirspeed,attackAng,slipAng,staticP,totalP] = import5HP(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [XSTEP,YSTEP,TRUEAIRSPEED,ATTACKANG,SLIPANG,STATICP,TOTALP] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [XSTEP,YSTEP,TRUEAIRSPEED,ATTACKANG,SLIPANG,STATICP,TOTALP] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [xStep,yStep,trueAirspeed,attackAng,slipAng,staticP,totalP] = importfile('RealWind202_Run1',25, 18457);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/05/01 08:55:03

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 25;
    endRow = inf;
end

%% Format for each line of text:
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%*s%*s%*s%*s%*s%*s%f%f%f%f%f%f%f%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
xStep = dataArray{:, 1};
yStep = dataArray{:, 2};
trueAirspeed = dataArray{:, 3};
attackAng = dataArray{:, 4};
slipAng = dataArray{:, 5};
staticP = dataArray{:, 6};
totalP = dataArray{:, 7};


